// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBsAeRHYBsG8776gGwa67zmT3foBRu-U',
    appId: '1:657004457465:web:9e7ce619b38c0273546128',
    messagingSenderId: '657004457465',
    projectId: 'linkspace-84e7f',
    authDomain: 'linkspace-84e7f.firebaseapp.com',
    storageBucket: 'linkspace-84e7f.firebasestorage.app',
    measurementId: 'G-896W2QWJBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNlxsuodPqAMAzFmgaoCsDe91uZvk1Eg',
    appId: '1:657004457465:android:be0e04240fa0c618546128',
    messagingSenderId: '657004457465',
    projectId: 'linkspace-84e7f',
    storageBucket: 'linkspace-84e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR99tuAvE8bI0iAGY6L_viW4TShEgmtug',
    appId: '1:657004457465:ios:c3d7151b3c1c888e546128',
    messagingSenderId: '657004457465',
    projectId: 'linkspace-84e7f',
    storageBucket: 'linkspace-84e7f.firebasestorage.app',
    iosBundleId: 'com.example.linkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR99tuAvE8bI0iAGY6L_viW4TShEgmtug',
    appId: '1:657004457465:ios:c3d7151b3c1c888e546128',
    messagingSenderId: '657004457465',
    projectId: 'linkspace-84e7f',
    storageBucket: 'linkspace-84e7f.firebasestorage.app',
    iosBundleId: 'com.example.linkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXBsAeRHYBsG8776gGwa67zmT3foBRu-U',
    appId: '1:657004457465:web:b74327341bb05707546128',
    messagingSenderId: '657004457465',
    projectId: 'linkspace-84e7f',
    authDomain: 'linkspace-84e7f.firebaseapp.com',
    storageBucket: 'linkspace-84e7f.firebasestorage.app',
    measurementId: 'G-KBD63CGLDB',
  );
}
